#-----------------------------------------------------------
# JDBC接続設定(DataSourceConfigurationProperitiesで読み込む)
#-----------------------------------------------------------
dbcp2.jdbc:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/petdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=JST&connectionTimeZone=SERVER
  username: root
  password: password
  initial-size: 1
  max-idle: 3
  min-idle: 1


#-----------------------------------------------------------
# MyBatis設定
#-----------------------------------------------------------
mybatis:
  mapper-locations: classpath:com/example/repository/mybatis/*xml


#-----------------------------------------------------------
# ログ設定(SQL発行周りをデバッグログでみる)
#-----------------------------------------------------------
logging.level:
  com.example.repository: debug
  org.springframework.jdbc.datasource.DataSourceTransactionManager: debug


#-----------------------------------------------------------
# アプリケーションを起動するたびにデーブルを更新する
#-----------------------------------------------------------
spring.datasource:
  url: jdbc:mysql://localhost:3306/petdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=JST&connectionTimeZone=SERVER
  username: root
  password: password
  driverClassName: com.mysql.cj.jdbc.Driver
  initialization-mode: alwayes
